### ISSUE TITLE
Null Check operator used on a null value Error 

### ISSUE THREAD

**Issue by purnimavenkatasubbu** [atsign-foundation/at_widgets#179]
**Describe the bug**
Null check operator used on a null value error is thrown while onboarding 

**To Reproduce**

1.  Install the wavi app
2.  Click on the generate free atsigns
3. Enter the email and OTP

**Expected behavior**
The error message should not be displayed in the logs

**Screenshots**
INFO|2021-09-02 13:00:33.619859|KeyChainUtil|atsignMap: {}
E/flutter (24013): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
E/flutter (24013): #0 _AtsignListScreenState.initState.<anonymous closure>
package:at_onboarding_flutter/screens/atsign_list_screen.dart:29
E/flutter (24013): #1 _rootRunUnary (dart:async/zone.dart:1362:47)
E/flutter (24013): #2 _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter (24013): <asynchronous suspension>

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A50
 - OS:  Android
 - Version [e.g. 59]

**Were you using an @‎application when the bug was found?**
  -  @ wavi
  
**Additional context**

**Comment by purnimavenkatasubbu** [comment]
Tested as part of this PR. 
https://github.com/atsign-foundation/at_widgets/pull/182

I don't see the exception in the logs

I/flutter ( 2815): {atsigns: [Caps, comfortabletabletennis, violetred7ready, emotionalbluebell, vicariouspuzzles, airsoftinvolved], newAtsign: 7anteaterugly3}
I/flutter ( 2815): INFO|2021-09-03 11:15:07.489508|KeyChainUtil|atsignMap: {}
I/ViewRootImpl@f982dd4MainActivity: ViewPostIme pointer 0
I/ViewRootImpl@f982dd4MainActivity: ViewPostIme pointer 1
I/ViewRootImpl@f982dd4MainActivity: ViewPostIme pointer 0
I/ViewRootImpl@f982dd4MainActivity: ViewPostIme pointer 1
I/flutter ( 2815): null
I/flutter ( 2815): INFO|2021-09-03 11:15:16.384670|KeyChainUtil|atsignMap: {}
I/flutter ( 2815): outbound finish handler called
I/flutter ( 2815): outbound finish handler called
I/flutter ( 2815): INFO|2021-09-03 11:15:30.892949|AtLookup|from result:data:_f9084139-f12d-43ed-a290-77e3077bbfd2@7anteaterugly3:0a031c30-2496-45c8-97df-3b133d7f7398
I/flutter ( 2815): INFO|2021-09-03 11:15:31.421307|AtLookup|auth success
I/flutter ( 2815): INFO|2021-09-03 11:15:34.059053|AtLookup|auth success
I/flutter ( 2815): INFO|2021-09-03 11:15:34.110060|KeyChainUtil|atsignMap: {}
I/flutter ( 2815): initializing storage
I/flutter ( 2815): INFO|2021-09-03 11:15:35.279109|CommitLogKeyStore|Keystore initialized successfully
I/flutter ( 2815): Hive instance has already been initialized. Please call Hive.init only once if possible.
I/flutter ( 2815): getHiveSecretFromFile no file found
I/flutter ( 2815): outbound finish handler called
I/flutter ( 2815): INFO|2021-09-03 11:15:35.551956|HivePersistenceManager|KeyStore initialized successfully
