### ISSUE TITLE
Unresolvable Kotlin version mismatch in at_backupkey_flutter

### ISSUE THREAD

**Issue by kmahon99** [atsign-foundation/at_widgets#377]
**Describe the bug**
In attempting to upgrade an app to the latest version of this package and Flutter in general, the app no longer builds. The following is shown:

Execution failed for task ':at_backupkey_flutter:compileDebugKotlin'.
Your project requires a newer version of the Kotlin Gradle plugin. 

**To Reproduce**
1. Perform a Flutter Upgrade & Flutter Pub Upgrade
2. Set the kotlin plugin version in the build.gradle to match the version used by the offending package (currently 1.3.50)
3. Perform a Flutter Clean
4. Perform a Flutter Pub Get

**Expected behavior**
The app should build and run as normal

**Screenshots**
![image](https://user-images.githubusercontent.com/10032032/156049177-f9edbfd1-83a9-4b0a-9b3d-53b2ec7b785a.png)

**Smartphone (please complete the following information):**
 - Device: Samsung S20 FE
 - OS: Android 12
 - Browser ?
 - Version ?

**Were you using an @‎application when the bug was found?**
  - No

**Comment by yahu1031** [comment]
Same with me too. Sometimes with at_onboarding_flutter package too.

**Comment by sarika01** [comment]
@kmahon99 With kotlin version `1.3.50`, one of `at_backupkey_flutter` package dependency, `file_saver` fails to build.

The example app is building fine with it's kotlin version `1.4.31`.
You can give this a try as quick fix.

We will let you know once the package is fixed.

**Comment by yahu1031** [comment]
```
Launching lib/main.dart on M2012K11AI in profile mode...
e: Incompatible classes were found in dependencies. Remove them from the classpath or use '-Xskip-metadata-version-check' to suppress errors
e: /Users/minnu/.gradle/caches/transforms-2/files-2.1/38d4abf4e5c97f7ea2cd15d5767edef8/jetified-kotlin-stdlib-jdk7-1.6.10.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
e: /Users/minnu/.gradle/caches/transforms-2/files-2.1/6c3f575daa2c3b547819c4dd6ff0ffa4/jetified-kotlin-stdlib-common-1.6.10.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
e: /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/Dialog.kt: (29, 9): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.

The class is loaded from /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/Dialog.kt: (31, 13): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
The class is loaded from /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/Dialog.kt: (46, 14): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
The class is loaded from /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/Dialog.kt: (47, 14): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
The class is loaded from /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/Dialog.kt: (54, 16): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
The class is loaded from /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/Dialog.kt: (55, 16): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
The class is loaded from /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/Dialog.kt: (58, 18): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
The class is loaded from /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/Dialog.kt: (62, 9): Class 'kotlin.coroutines.CoroutineContext' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
The class is loaded from /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/coroutines/CoroutineContext.class
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/Dialog.kt: (62, 42): Class 'kotlin.coroutines.CoroutineContext' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
The class is loaded from /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/coroutines/CoroutineContext.class
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/Dialog.kt: (63, 13): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
The class is loaded from /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/Dialog.kt: (64, 17): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
The class is loaded from /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/Dialog.kt: (65, 25): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
The class is loaded from /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/Dialog.kt: (69, 25): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
The class is loaded from /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/Dialog.kt: (72, 25): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
The class is loaded from /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/Dialog.kt: (81, 13): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
The class is loaded from /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/Dialog.kt: (84, 17): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
The class is loaded from /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/Dialog.kt: (101, 29): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
The class is loaded from /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/Dialog.kt: (105, 28): Unresolved reference: startsWith
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/Dialog.kt: (106, 35): Unresolved reference: replaceFirst
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/Dialog.kt: (106, 55): Unresolved reference: toRegex
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/Dialog.kt: (122, 39): Unresolved reference: replaceFirst
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/Dialog.kt: (130, 24): Unresolved reference: startsWith

e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/Dialog.kt: (131, 31): Unresolved reference: replaceFirst
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/Dialog.kt: (131, 51): Unresolved reference: toRegex
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/Dialog.kt: (133, 17): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
The class is loaded from /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/Dialog.kt: (139, 23): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
The class is loaded from /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/Dialog.kt: (158, 9): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
The class is loaded from /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/Dialog.kt: (168, 21): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
The class is loaded from /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/Dialog.kt: (181, 61): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
The class is loaded from /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/FileSaverPlugin.kt: (37, 9): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
The class is loaded from /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/FileSaverPlugin.kt: (39, 9): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
The class is loaded from /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/FileSaverPlugin.kt: (40, 24): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
The class is loaded from /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/FileSaverPlugin.kt: (45, 9): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
The class is loaded from /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/FileSaverPlugin.kt: (46, 9): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
The class is loaded from /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/FileSaverPlugin.kt: (47, 24): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
The class is loaded from /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class

e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/FileSaverPlugin.kt: (57, 18): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
The class is loaded from /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/FileSaverPlugin.kt: (58, 13): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
The class is loaded from /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/FileSaverPlugin.kt: (62, 28): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
The class is loaded from /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/FileSaverPlugin.kt: (66, 30): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
The class is loaded from /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/FileSaverPlugin.kt: (71, 28): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
The class is loaded from /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/FileSaverPlugin.kt: (83, 18): Unresolved reference: writeBytes
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/FileSaverPlugin.kt: (91, 23): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
The class is loaded from /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/FileSaverPlugin.kt: (92, 13): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
The class is loaded from /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/FileSaverPlugin.kt: (94, 9): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
The class is loaded from /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/FileSaverPlugin.kt: (99, 14): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
The class is loaded from /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/FileSaverPlugin.kt: (104, 14): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
The class is loaded from /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/FileSaverPlugin.kt: (110, 23): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
The class is loaded from /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/FileSaverPlugin.kt: (111, 13): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.

The class is loaded from /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/FileSaverPlugin.kt: (113, 9): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
The class is loaded from /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/FileSaverPlugin.kt: (119, 9): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
The class is loaded from /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/FileSaverPlugin.kt: (123, 24): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
The class is loaded from /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/FileSaverPlugin.kt: (126, 41): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
The class is loaded from /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/minnu/.pub-cache/hosted/pub.dartlang.org/file_saver-0.0.12/android/src/main/kotlin/com/one/file_saver/FileSaverPlugin.kt: (128, 14): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
The class is loaded from /Users/minnu/.gradle/caches/transforms-2/files-2.1/f050b28dc765f9879312e493365b6821/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class


FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':file_saver:compileProfileKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 32s
┌─ Flutter Fix ────────────────────────────────────────────────────────────────────────────────┐
│ [!] Your project requires a newer version of the Kotlin Gradle plugin.                       │
│ Find the latest version on https://kotlinlang.org/docs/gradle.html#plugin-and-versions, then │
│ update /Users/minnu/Documents/Flutter/The @platform/apps/contacts-app/android/build.gradle:  │
│ ext.kotlin_version = '<latest-version>'                                                      │
└──────────────────────────────────────────────────────────────────────────────────────────────┘
Exception: Gradle task assembleProfile failed with exit code 1
#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:431:9)
<asynchronous suspension>
#2      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:179:5)
<asynchronous suspension>
#3      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:579:7)
<asynchronous suspension>
#4      FlutterDevice.runCold (package:flutter_tools/src/resident_runner.dart:501:33)
<asynchronous suspension>
#5      ColdRunner.run (package:flutter_tools/src/run_cold.dart:71:28)
<asynchronous suspension>
#6      AppDomain.launch.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:621:9)
<asynchronous suspension>
#7      AppDomain.launch (package:flutter_tools/src/commands/daemon.dart:619:5)
<asynchronous suspension>
#8      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:571:15)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     main (package:flutter_tools/executable.dart:94:3)
<asynchronous suspension>

Exited (sigterm)
```

these are the logs for `1.4.31`

**Comment by sarika01** [comment]
@yahu1031 What is your project's `compileSdkVersion` and `minSdkVersion` ?

**Comment by yahu1031** [comment]
@sarika01 

```gradle
minSdkVersion 24
targetSdkVersion 30
compileSdkVersion 31
```

**Comment by sarika01** [comment]
@yahu1031 what is your app's `com.android.tools.build:gradle` version in dependencies?

**Comment by yahu1031** [comment]
`4.0.1` - Buzz app

**Comment by kmahon99** [comment]
> 

@sarika01 that version of kotlin gives the same error unfortunately. Has there been any progress on this at all? Haven't been able to launch my app in over 2 weeks.

**Comment by sarika01** [comment]
@kmahon99 The example app works fine at my end. Can you please try this combination of kotlin version and gradle tools version?
```
buildscript {
    ext.kotlin_version = '1.5.10'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
```

**Comment by kmahon99** [comment]
Apologies for the late response, been away for a while. I've tried the above combination and now I'm getting a different error:
![image](https://user-images.githubusercontent.com/10032032/161441119-6b8e5eed-7567-4922-a84b-5d65f4106ea9.png)
This seems to be something to do with null safety in an at_client package, is this a known issue?

**Comment by yahu1031** [comment]
Not related here and BTW pull the latest version.

**Comment by kmahon99** [comment]
Thanks, the latest packages seems to fix both of these issues.
